---
services:
  postgres_z:
    container_name: postgres_z106
    image: postgres:14-alpine
    restart: unless-stopped
    ports:
      - 35432:5432 # API
    volumes:
      - ./data/datasets:/src
      - ./src/sql:/docker-entrypoint-initdb.d
  
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

  minio:
      image: minio/minio
      container_name: minioserver
      ports:
        - 9000:9000 # API
        - 9001:9001 # GUI
      env_file:
      - .env
      environment:
        MINIO_ROOT_USER: ${MINIO_ROOT_USER}
        MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
      volumes: 
      - ./data/volumes/minio/data:/data
      command: server /data --console-address ":9001"
  

  